openapi: 3.0.3
info:
  title: Accounts Service
  version: 1.0.0
paths:
  /accounts/getByUserId:
    get:
      tags:
        - accounts
      description: Get user accounts
      summary: Get user accounts
      parameters:
        - name: userId
          in: query
          description: Account owner Id
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Received accounts info
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    number:
                      type: string
                    amount:
                      type: integer
                    status:
                      type: string
                    ownerId:
                      type: string
        '400': &badRequest
          description: Request is missing required fields or has invalid fields
        '401': &unauthorized
          description: Unauthorized
  /account/getByNumber:
    get:
      tags:
        - account
      description: Get short bank account info
      summary: Get short bank account info
      parameters:
        - name: number
          in: query
          description: Account Number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Received an account info
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  number:
                    type: string
                  status:
                    type: string
                  owner:
                    type: object
                    properties:
                      id:
                        type: string
                      firstName: 
                        type: string
                      lastName:
                        type: string
        '400': *badRequest
        '401': *unauthorized
  /transaction/blockAmount:
    post:
      tags:
        - transaction
      description: Block an ammount due to initiated transaction
      summary: Block an ammount due to initiated transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                senderAccountId:
                  type: string
                receiverAccountId:
                  type: string
                amount:
                  type: integer
      responses:
        '200': &ok
          description: OK
        '201':
          description: Created
        '400': *badRequest
        '401': *unauthorized
  /transaction/confirm:
    post:
      tags:
        - transaction
      description: Confirm previously initiated transaction by SMS code
      summary: Confirm previously initiated transaction by SMS code
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                smsCode: 
                  type: string
      responses:
        '200': *ok
        '400': *badRequest
        '401': *unauthorized